services:
  pbs-exporter:
    build:
      context: .
    image: pbs-exporter
    container_name: pbs-exporter
    user: '65534'
    restart: always
    ports:
      - "10019:10019"
    environment:
      - PBS_USERNAME=monitoring@pbs
      - PBS_API_TOKEN_NAME=monitoring-pbs-exporter
      - PBS_API_TOKEN=
      - PBS_INSECURE=true
      - PBS_TIMEOUT=120s
      - PBS_LOGLEVEL=debug
      - PBS_LISTEN_ADDRESS=0.0.0.0:10019
